### PR TITLE
EIC code downloader functions and ...TypeList meta tables are added

### PR DESCRIPTION
**Pull request by sbudai**
I have taken your word seriously and felt free to add PR. 
...TypeList tables are coming from entso-e-code-list-v36r0.pdf document

### CODE REVIEW

**Comment by krose** [comment]
That's an awesome pull request! Well done. 

Just one remark. It seems like external data should be put in the /inst folder according to Hadley's book here r-pkgs.org/data.html
I think it's good to follow the standards on this, but I'm not sure if it is a strict demand. What do you think?

**Comment by sbudai** [comment]
I interpreted that chapter as if I want to store the data as raw data (csv), then I shoud put them into /inst, but if I want to store them as binary, then I should put them (as raw) into the /data-raw folder and create the binary alternatives with calling usethis::use_data() function within scripts as it is done here: https://github.com/tidyverse/ggplot2/tree/main/data-raw
Am I wrong or missed the point? (I am not an expert package maker guy.)

**Comment by krose** [comment]
Thanks again.

**Comment by krose** [comment]
Hi. I've been very busy at work and I simply forgot. I've just merged

søn. 6. feb. 2022 21.43 skrev Sandor Budai ***@***.***>:

**Pull request merged**
